### ISSUE TITLE
Show target's language in pseudo-element

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#120]
Pretty easy, and would be valuable for users:
```css
[hreflang]::after {
    content: attr(hreflang);
}
```
