### ISSUE TITLE
scroll-padding on :root

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#143]
Try [@fvsch's idea to use `scroll-padding` to give scroll a breathe](https://twitter.com/fvsch/status/1190277947871105027) and [its reduced test case](https://twitter.com/fvsch/status/1190353802802737152).

```css
:root {
  scroll-behavior: smooth;
  scroll-padding: 1rem;
}
```
