### ISSUE TITLE
Use  prefers-reduced-motion query?

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#18]
Would something like:
```css
@media screen and (prefers-reduced-motion: reduce) {
  * {
    animation: none !important;
    transition: none !important;
  }
}
```
ever be helpful?
