### ISSUE TITLE
Scroll handling

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#186]
A few things to improve.

## Spacing

From [Stephanie Eckles's "Modern CSS Toolkit'](https://codepen.io/5t3ph/pen/LYzvrGv):
```css
a {
  scroll-margin-bottom: 8vh;
}

[id] {
  scroll-margin-top: 1vh;
}
```

## Smooth scroll

Only set `scroll-behaviour: smooth` when `prefers-reduced-motion` is explicitly set to `no-preference`, [as implemented in Bootstrap](https://github.com/twbs/bootstrap/blob/cd208341a198f22f60f20e674b8060d5e7d65f92/scss/_reboot.scss#L33).

## Scroll chaining

And maybe some use cases for `overscroll-behavior`? Have a look at [Ahmad Shadeed post regarding scroll chaining](https://ishadeed.com/article/prevent-scroll-chaining-overscroll-behavior/).
