### ISSUE TITLE
Set `touch-action`on a, button

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#187]
As [explained by Adam Argyle on Twitter](https://twitter.com/argyleink/status/1405881231695302659/photo/1), `touch-action: manipulation;` on links and buttons make them faster to react.

```css
a, button {
  touch-action: manipulation;
}
```
