### ISSUE TITLE
Hide outline on focusable anchors when hovering body

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#32]
Something like:
```css
body:hover [tabindex="-1"]:focus {
    outline-color: transparent;
}
```

See [Heydon's tweet](https://twitter.com/heydonworks/status/594115773871824897) and [Amelia Bellamy-Royds'](https://twitter.com/AmeliasBrain/status/1026521723888226304).
