### ISSUE TITLE
Try :focus-visible pseudo-class

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#33]
Might be *very* useful.

```css
:focus:not(:focus-visible) { 
    /* here, and only here, you may remove the outline */
}
```
Some reading: [":focus-visible and backwards compatibility"](https://developer.paciellogroup.com/blog/2018/03/focus-visible-and-backwards-compatibility/) by Patrick H. Lauke on The Paciello Group's blog.

And there's [some inspirations in Fiancial Times mixins](https://github.com/Financial-Times/o-normalise/blob/984a0fa8178c35ac2089651c9e86602f86edcde3/src/scss/_mixins.scss).

**Comment by ffoodd** [comment]
Reopening with [@fvsch's tweet inspiration](https://twitter.com/fvsch/status/1161930384332001280) and reading agin [`:focus-visible`'s polyfill](https://github.com/WICG/focus-visible).

Could worth it, and at least sseeeedd's a great place to play with it.

**Comment by ffoodd** [comment]
Also a very basic handy way to use it is:
```scss
// Using the :focus-visible polyfill to hide outline defensively
// See https://github.com/WICG/focus-visible
.js-focus-visible :focus:not(.focus-visible) {
  outline: 0 !important;
}
```

But FWIW, I think I should go with CSS only (without polyfilling).
