### ISSUE TITLE
Allow keyword for sizes animation

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#413]
Using this simple snippet:

```css
:root {
    interpolate-size: allow-keywords; /* 👈 */
}

```

Would help transitionig `details`' content, for example. [More info on web.dev](https://developer.chrome.com/docs/css-ui/animate-to-height-auto/)
