### ISSUE TITLE
Allow basic view transitions

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#453]
As simple as:

```css
@view-transition {
  navigation: auto;
}
```

Not baseline yet (missing Firefox) but doesn't cost anything.

See [Adam Argyle <cite>6 CSS snippets for 2025</cite> post](https://nerdy.dev/6-css-snippets-every-front-end-developer-should-know-in-2025#view-transitions-for-page-navigation).

**Comment by ffoodd** [comment]
Improved to take user preference into account:

```css
@media screen and (prefers-reduced-motion: no-preference) {
  @view-transition {
    navigation: auto;
  }
}
```


See [Ariel Salminen's <cite>View transitions for any website</cite> blog post](https://arielsalminen.com/2025/view-transitions-for-any-website/).
