### ISSUE TITLE
Basic animations for details & popover

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#454]
`@starting-style` unveils easy defaults for transitions of such native elements, as stated by [Adam Argyle in <cite>6 CSS snippets for 2025</cite> post](https://nerdy.dev/6-css-snippets-every-front-end-developer-should-know-in-2025#transition-animation-for-%3Ccode%3E%3Cdialog%3E%3C/code%3E-and-%3Ccode%3E[popover]%3C/code%3E).

```css
/* enable transitions, allow-discrete, define timing */
[popover], dialog, ::backdrop {
  transition: display 1s allow-discrete, overlay 1s allow-discrete, opacity 1s;
  opacity: 0;
}

/* ON STAGE */
:popover-open,
:popover-open::backdrop,
[open],
[open]::backdrop {
  opacity: 1;
}

/* OFF STAGE */
/* starting-style for pre-positioning (enter stage from here) */
@starting-style {
  :popover-open,
  :popover-open::backdrop,
  [open],
  [open]::backdrop {
    opacity: 0;
  }
}
```
