### ISSUE TITLE
Use the pointer MQ

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#68]
`pointer` media query allows to know pointer accuracy.
We can use it to increase interactive elements' sizing if a low accuracy pointer is used, for example. I'm pretty sure there's a lot more to find about this :)

Some reading:
* [MDN article about the `pointer` MQ](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer)

**Comment by ffoodd** [comment]
Could be interesting along with [`hover` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover).

**Comment by ffoodd** [comment]
Is something like this a good idea:
```css
:root {
    --gutter: 1em;
}

@media (pointer: coarse) {
    :root {
        --gutter: 1.5em;
    }
}
```

Waiting for more sources and opinions :)
