### ISSUE TITLE
Improve hyphens

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#95]
Using some more CSS could be great to improve hyphenation:
```css
p {
    hyphens: auto;
    hyphenate-limit-chars: 6 3 3;
    hyphenate-limit-lines: 2;   
    hyphenate-limit-last: always;
    hyphenate-limit-zone: 8%;
}
```

Detailed reading [on Richard Rutter's blog post about hyphenation](http://clagnut.com/blog/2395)
